services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=123456!
      - POSTGRES_USER=postgres!
      - POSTGRES_DB=desafio
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"